[package]
name = "llvm-safe"
version = "0.1.0"
authors = ["Jonathan S <gereeter+code@gmail.com>"]

[dependencies]
libc = "0.2"
llvm-sys = ">= 39.0.0, < 51.0.0"

[dev-dependencies]
const-cstr-fork = "0.2.2"
